# -*- coding: utf-8 -*-

# Form implementation generated from ..reading ui file 'coolingwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CoolingWidget(object):
    def setupUi(self, CoolingWidget):
        CoolingWidget.setObjectName("CoolingWidget")
        CoolingWidget.resize(307, 218)
        self.verticalLayout = QtWidgets.QVBoxLayout(CoolingWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(CoolingWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelStatus = QtWidgets.QLineEdit(self.groupBox_2)
        self.labelStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatus.setReadOnly(True)
        self.labelStatus.setObjectName("labelStatus")
        self.gridLayout_2.addWidget(self.labelStatus, 0, 1, 1, 1)
        self.buttonApply = QtWidgets.QPushButton(self.groupBox_2)
        self.buttonApply.setObjectName("buttonApply")
        self.gridLayout_2.addWidget(self.buttonApply, 4, 1, 1, 1)
        self.checkEnabled = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkEnabled.setObjectName("checkEnabled")
        self.gridLayout_2.addWidget(self.checkEnabled, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.spinSetPoint = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spinSetPoint.setMinimum(-50.0)
        self.spinSetPoint.setMaximum(50.0)
        self.spinSetPoint.setObjectName("spinSetPoint")
        self.gridLayout_2.addWidget(self.spinSetPoint, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.labelPower = QtWidgets.QLineEdit(self.groupBox_2)
        self.labelPower.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPower.setReadOnly(True)
        self.labelPower.setObjectName("labelPower")
        self.gridLayout_2.addWidget(self.labelPower, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 2)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(CoolingWidget)
        QtCore.QMetaObject.connectSlotsByName(CoolingWidget)

    def retranslateUi(self, CoolingWidget):
        _translate = QtCore.QCoreApplication.translate
        CoolingWidget.setWindowTitle(_translate("CoolingWidget", "Form"))
        self.groupBox_2.setTitle(_translate("CoolingWidget", "Cooling"))
        self.buttonApply.setText(_translate("CoolingWidget", "Apply"))
        self.checkEnabled.setText(_translate("CoolingWidget", "Enabled"))
        self.label_9.setText(_translate("CoolingWidget", "Status:"))
        self.spinSetPoint.setSuffix(_translate("CoolingWidget", " °C"))
        self.label.setText(_translate("CoolingWidget", "SetPoint:"))
        self.label_10.setText(_translate("CoolingWidget", "Power:"))
