# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modewidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModeWidget(object):
    def setupUi(self, ModeWidget):
        ModeWidget.setObjectName("ModeWidget")
        ModeWidget.resize(229, 87)
        self.verticalLayout = QtWidgets.QVBoxLayout(ModeWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(ModeWidget)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.textStatus = QtWidgets.QLineEdit(self.groupBox)
        self.textStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.textStatus.setReadOnly(True)
        self.textStatus.setObjectName("textStatus")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textStatus)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(ModeWidget)
        QtCore.QMetaObject.connectSlotsByName(ModeWidget)

    def retranslateUi(self, ModeWidget):
        _translate = QtCore.QCoreApplication.translate
        ModeWidget.setWindowTitle(_translate("ModeWidget", "Form"))
        self.groupBox.setTitle(_translate("ModeWidget", "Modes"))
        self.label_11.setText(_translate("ModeWidget", "Status:"))


from . import resources_rc
