# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgettelescope.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WidgetTelescope(object):
    def setupUi(self, WidgetTelescope):
        WidgetTelescope.setObjectName("WidgetTelescope")
        WidgetTelescope.resize(891, 651)
        self.horizontalLayout = QtWidgets.QHBoxLayout(WidgetTelescope)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupStatus = QtWidgets.QGroupBox(WidgetTelescope)
        self.groupStatus.setObjectName("groupStatus")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupStatus)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.labelStatus = QtWidgets.QLineEdit(self.groupStatus)
        self.labelStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatus.setReadOnly(True)
        self.labelStatus.setObjectName("labelStatus")
        self.gridLayout_5.addWidget(self.labelStatus, 0, 0, 1, 2)
        self.butInit = QtWidgets.QPushButton(self.groupStatus)
        self.butInit.setObjectName("butInit")
        self.gridLayout_5.addWidget(self.butInit, 1, 0, 1, 1)
        self.butPark = QtWidgets.QPushButton(self.groupStatus)
        self.butPark.setObjectName("butPark")
        self.gridLayout_5.addWidget(self.butPark, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupStatus)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.labelCurRA = QtWidgets.QLineEdit(self.groupStatus)
        self.labelCurRA.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCurRA.setReadOnly(True)
        self.labelCurRA.setObjectName("labelCurRA")
        self.gridLayout.addWidget(self.labelCurRA, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupStatus)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.labelCurDec = QtWidgets.QLineEdit(self.groupStatus)
        self.labelCurDec.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCurDec.setReadOnly(True)
        self.labelCurDec.setObjectName("labelCurDec")
        self.gridLayout.addWidget(self.labelCurDec, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupStatus)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.labelCurAlt = QtWidgets.QLineEdit(self.groupStatus)
        self.labelCurAlt.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCurAlt.setReadOnly(True)
        self.labelCurAlt.setObjectName("labelCurAlt")
        self.gridLayout.addWidget(self.labelCurAlt, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupStatus)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.labelCurAz = QtWidgets.QLineEdit(self.groupStatus)
        self.labelCurAz.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCurAz.setReadOnly(True)
        self.labelCurAz.setObjectName("labelCurAz")
        self.gridLayout.addWidget(self.labelCurAz, 3, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_4.addWidget(self.groupStatus)
        self.groupBox_3 = QtWidgets.QGroupBox(WidgetTelescope)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.spinMoveAlt = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spinMoveAlt.setDecimals(3)
        self.spinMoveAlt.setMaximum(90.0)
        self.spinMoveAlt.setSingleStep(10.0)
        self.spinMoveAlt.setObjectName("spinMoveAlt")
        self.gridLayout_3.addWidget(self.spinMoveAlt, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.spinMoveAz = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spinMoveAz.setDecimals(3)
        self.spinMoveAz.setMaximum(360.0)
        self.spinMoveAz.setSingleStep(10.0)
        self.spinMoveAz.setObjectName("spinMoveAz")
        self.gridLayout_3.addWidget(self.spinMoveAz, 1, 1, 1, 1)
        self.butMove = QtWidgets.QPushButton(self.groupBox_3)
        self.butMove.setObjectName("butMove")
        self.gridLayout_3.addWidget(self.butMove, 2, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(WidgetTelescope)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.textTrackRA = QtWidgets.QLineEdit(self.groupBox_4)
        self.textTrackRA.setObjectName("textTrackRA")
        self.gridLayout_4.addWidget(self.textTrackRA, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)
        self.textTrackDec = QtWidgets.QLineEdit(self.groupBox_4)
        self.textTrackDec.setObjectName("textTrackDec")
        self.gridLayout_4.addWidget(self.textTrackDec, 1, 1, 1, 1)
        self.butTrack = QtWidgets.QPushButton(self.groupBox_4)
        self.butTrack.setObjectName("butTrack")
        self.gridLayout_4.addWidget(self.butTrack, 2, 1, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_4.setColumnStretch(1, 2)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.widgetPlot = QtWidgets.QWidget(WidgetTelescope)
        self.widgetPlot.setObjectName("widgetPlot")
        self.horizontalLayout.addWidget(self.widgetPlot)
        self.widgetSidebar = QtWidgets.QWidget(WidgetTelescope)
        self.widgetSidebar.setObjectName("widgetSidebar")
        self.horizontalLayout.addWidget(self.widgetSidebar)
        self.horizontalLayout.setStretch(1, 1)

        self.retranslateUi(WidgetTelescope)
        QtCore.QMetaObject.connectSlotsByName(WidgetTelescope)

    def retranslateUi(self, WidgetTelescope):
        _translate = QtCore.QCoreApplication.translate
        WidgetTelescope.setWindowTitle(_translate("WidgetTelescope", "Form"))
        self.groupStatus.setTitle(_translate("WidgetTelescope", "Status"))
        self.butInit.setText(_translate("WidgetTelescope", "Init"))
        self.butPark.setText(_translate("WidgetTelescope", "Park"))
        self.label.setText(_translate("WidgetTelescope", "RA:"))
        self.label_2.setText(_translate("WidgetTelescope", "Dec:"))
        self.label_3.setText(_translate("WidgetTelescope", "Alt:"))
        self.label_4.setText(_translate("WidgetTelescope", "Az:"))
        self.groupBox_3.setTitle(_translate("WidgetTelescope", "Move Alt/Az"))
        self.label_5.setText(_translate("WidgetTelescope", "Alt:"))
        self.spinMoveAlt.setSuffix(_translate("WidgetTelescope", "°"))
        self.label_6.setText(_translate("WidgetTelescope", "Az:"))
        self.spinMoveAz.setSuffix(_translate("WidgetTelescope", "°"))
        self.butMove.setText(_translate("WidgetTelescope", "Move"))
        self.groupBox_4.setTitle(_translate("WidgetTelescope", "Track RA/Dec"))
        self.label_7.setText(_translate("WidgetTelescope", "RA:"))
        self.label_8.setText(_translate("WidgetTelescope", "Dec:"))
        self.butTrack.setText(_translate("WidgetTelescope", "Track"))

