# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgetdatadisplay.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetDataDisplay(object):
    def setupUi(self, WidgetDataDisplay):
        WidgetDataDisplay.setObjectName("WidgetDataDisplay")
        WidgetDataDisplay.resize(512, 388)
        self.verticalLayout = QtWidgets.QVBoxLayout(WidgetDataDisplay)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(WidgetDataDisplay)
        self.tabWidget.setObjectName("tabWidget")
        self.tabImage = QtWidgets.QWidget()
        self.tabImage.setObjectName("tabImage")
        self.tabWidget.addTab(self.tabImage, "")
        self.tabFitsHeader = QtWidgets.QWidget()
        self.tabFitsHeader.setObjectName("tabFitsHeader")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabFitsHeader)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableFitsHeader = QtWidgets.QTableWidget(self.tabFitsHeader)
        self.tableFitsHeader.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableFitsHeader.setAlternatingRowColors(True)
        self.tableFitsHeader.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableFitsHeader.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableFitsHeader.setObjectName("tableFitsHeader")
        self.tableFitsHeader.setColumnCount(0)
        self.tableFitsHeader.setRowCount(0)
        self.tableFitsHeader.horizontalHeader().setStretchLastSection(True)
        self.tableFitsHeader.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tableFitsHeader)
        self.tabWidget.addTab(self.tabFitsHeader, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkAutoUpdate = QtWidgets.QCheckBox(WidgetDataDisplay)
        self.checkAutoUpdate.setChecked(True)
        self.checkAutoUpdate.setObjectName("checkAutoUpdate")
        self.horizontalLayout.addWidget(self.checkAutoUpdate)
        spacerItem = QtWidgets.QSpacerItem(38, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.checkAutoSave = QtWidgets.QCheckBox(WidgetDataDisplay)
        self.checkAutoSave.setObjectName("checkAutoSave")
        self.horizontalLayout.addWidget(self.checkAutoSave)
        self.textAutoSavePath = QtWidgets.QLineEdit(WidgetDataDisplay)
        self.textAutoSavePath.setEnabled(False)
        self.textAutoSavePath.setObjectName("textAutoSavePath")
        self.horizontalLayout.addWidget(self.textAutoSavePath)
        self.butAutoSave = QtWidgets.QToolButton(WidgetDataDisplay)
        self.butAutoSave.setObjectName("butAutoSave")
        self.horizontalLayout.addWidget(self.butAutoSave)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.butSaveTo = QtWidgets.QToolButton(WidgetDataDisplay)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/Crystal_Clear_device_floppy_unmount.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butSaveTo.setIcon(icon)
        self.butSaveTo.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.butSaveTo.setObjectName("butSaveTo")
        self.horizontalLayout.addWidget(self.butSaveTo)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(WidgetDataDisplay)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WidgetDataDisplay)

    def retranslateUi(self, WidgetDataDisplay):
        _translate = QtCore.QCoreApplication.translate
        WidgetDataDisplay.setWindowTitle(_translate("WidgetDataDisplay", "Form"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabImage), _translate("WidgetDataDisplay", "Image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFitsHeader), _translate("WidgetDataDisplay", "FITS header"))
        self.checkAutoUpdate.setText(_translate("WidgetDataDisplay", "Auto-update"))
        self.checkAutoSave.setText(_translate("WidgetDataDisplay", "Auto-save:"))
        self.butAutoSave.setText(_translate("WidgetDataDisplay", "..."))
        self.butSaveTo.setText(_translate("WidgetDataDisplay", "Save to..."))
