# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1232, 723)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitterLog = QtWidgets.QSplitter(self.centralwidget)
        self.splitterLog.setOrientation(QtCore.Qt.Vertical)
        self.splitterLog.setObjectName("splitterLog")
        self.widget = QtWidgets.QWidget(self.splitterLog)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 92, 490))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.menuShell = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.menuShell.setMinimumSize(QtCore.QSize(80, 100))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/Crystal_Clear_app_terminal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuShell.setIcon(icon)
        self.menuShell.setIconSize(QtCore.QSize(64, 64))
        self.menuShell.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.menuShell.setAutoRaise(False)
        self.menuShell.setObjectName("menuShell")
        self.verticalLayout_5.addWidget(self.menuShell)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.splitterToolBox = QtWidgets.QSplitter(self.widget)
        self.splitterToolBox.setOrientation(QtCore.Qt.Horizontal)
        self.splitterToolBox.setObjectName("splitterToolBox")
        self.stackedWidget = QtWidgets.QStackedWidget(self.splitterToolBox)
        self.stackedWidget.setObjectName("stackedWidget")
        self.toolBox = QtWidgets.QToolBox(self.splitterToolBox)
        self.toolBox.setObjectName("toolBox")
        self.pageHelp = QtWidgets.QWidget()
        self.pageHelp.setObjectName("pageHelp")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pageHelp)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textHelp = QtWidgets.QTextBrowser(self.pageHelp)
        self.textHelp.setObjectName("textHelp")
        self.verticalLayout_2.addWidget(self.textHelp)
        self.toolBox.addItem(self.pageHelp, "")
        self.pageClients = QtWidgets.QWidget()
        self.pageClients.setGeometry(QtCore.QRect(0, 0, 500, 394))
        self.pageClients.setObjectName("pageClients")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.pageClients)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listClients = QtWidgets.QListWidget(self.pageClients)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listClients.sizePolicy().hasHeightForWidth())
        self.listClients.setSizePolicy(sizePolicy)
        self.listClients.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listClients.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listClients.setObjectName("listClients")
        self.verticalLayout.addWidget(self.listClients)
        self.toolBox.addItem(self.pageClients, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 500, 394))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableVariables = QtWidgets.QTableWidget(self.page_2)
        self.tableVariables.setObjectName("tableVariables")
        self.tableVariables.setColumnCount(0)
        self.tableVariables.setRowCount(0)
        self.tableVariables.horizontalHeader().setStretchLastSection(True)
        self.tableVariables.verticalHeader().setVisible(False)
        self.verticalLayout_4.addWidget(self.tableVariables)
        self.toolBox.addItem(self.page_2, "")
        self.horizontalLayout.addWidget(self.splitterToolBox)
        self.horizontalLayout.setStretch(1, 1)
        self.tableLog = QtWidgets.QTableView(self.splitterLog)
        self.tableLog.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableLog.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableLog.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableLog.setGridStyle(QtCore.Qt.NoPen)
        self.tableLog.setSortingEnabled(False)
        self.tableLog.setObjectName("tableLog")
        self.tableLog.horizontalHeader().setVisible(False)
        self.tableLog.horizontalHeader().setStretchLastSection(True)
        self.tableLog.verticalHeader().setVisible(False)
        self.tableLog.verticalHeader().setDefaultSectionSize(20)
        self.tableLog.verticalHeader().setMinimumSectionSize(20)
        self.gridLayout.addWidget(self.splitterLog, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(-1)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "pytel supervisor"))
        self.menuShell.setText(_translate("MainWindow", "Shell"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageHelp), _translate("MainWindow", "Help"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageClients), _translate("MainWindow", "Clients"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Variables"))

from . import resources_rc
