name: Publish package to PyPI
on:
  push:
    tags:
    - 'v*'
jobs:
  build-n-publish:
    name: Build and publish package to PyPI
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Install poetry
        run: |
          curl -fsS -o get-poetry.py https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
          python get-poetry.py -y
      - name: Configure poetry
        run: $HOME/.poetry/bin/poetry config virtualenvs.in-project true
      - name: Set up cache
        uses: actions/cache@v1
        id: cache
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Ensure cache is healthy
        if: steps.cache.outputs.cache-hit == 'true'
        run: $HOME/.poetry/bin/poetry run pip --version >/dev/null 2>&1 || rm -rf .venv
      - name: Install Dependencies
        run: $HOME/.poetry/bin/poetry install
      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.pypi_password }}
        run: |
          $HOME/.poetry/bin/poetry config pypi-token.pypi $PYPI_TOKEN
          $HOME/.poetry/bin/poetry publish --build
